# SPDX-FileCopyrightText: 2025 Revelation Team
#
# SPDX-License-Identifier: MIT

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "target/**"

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 5%
      - type: patch
        target: 80%
  individual_flags:
    - name: lib
      paths:
        - "src/**"
      carryforward: true
      statuses:
        - type: project
          target: auto
        - type: patch
          target: 80%
